"""
report.py - Report Generator & Secure Sanitization Artifacts
Part of CodeSanitizer - AI-Generated Code & Package Hallucination Auditor.

Generates:
1. Markdown / Plaintext Security Reports
2. Structured JSON Audit Artifacts
3. Sanitized .env.example files for detected hardcoded secrets
"""

import json
from typing import Dict, List, Any
from rules import VulnerabilityFinding, SEVERITY_ICONS


def generate_markdown_report(analysis_result: Dict[str, Any], filename: str = "submitted_code.py") -> str:
    """Generates a professional Markdown security audit report."""
    if not analysis_result.get("success"):
        return f"# 🛡️ CodeSanitizer Security Audit Report\n\n**Status:** Analysis Failed\n**Error:** {analysis_result.get('message')}"

    summary = analysis_result["summary"]
    findings: List[VulnerabilityFinding] = analysis_result["findings"]
    packages = analysis_result.get("packages", [])

    lines = []
    lines.append("# 🛡️ CodeSanitizer Security Audit Report")
    lines.append(f"**Target:** `{filename}` | **Lines Analyzed:** {analysis_result.get('code_lines_count', 'N/A')}")
    lines.append("")
    lines.append("## 📊 Executive Summary")
    lines.append(f"- **Security Score:** **{summary['score']} / 100** ({summary['badge']})")
    lines.append(f"- **Total Findings:** {summary['total_findings']}")
    lines.append(f"- **Critical:** {summary['counts'].get('CRITICAL', 0)} | **High:** {summary['counts'].get('HIGH', 0)} | **Medium:** {summary['counts'].get('MEDIUM', 0)} | **Low:** {summary['counts'].get('LOW', 0)}")
    lines.append(f"- **Calculation Logic:** {summary['explanation']}")
    lines.append("")

    # Package Section
    lines.append("## 📦 Package Verification & Supply Chain Audit")
    if not packages:
        lines.append("*No external package imports detected.*")
    else:
        lines.append("| Package | Status | PyPI Verified | Description / Warning |")
        lines.append("| :--- | :---: | :---: | :--- |")
        for pkg in packages:
            status_badge = "✅ Verified" if pkg.status == "VERIFIED" else ("❌ Not Found" if pkg.status == "NOT_FOUND" else "📘 Stdlib")
            desc = pkg.summary if pkg.status == "VERIFIED" and pkg.summary else pkg.message
            lines.append(f"| `{pkg.package_name}` | {pkg.status} | {status_badge} | {desc} |")
    lines.append("")

    # Vulnerability Section
    lines.append("## 🔍 Detailed Vulnerability Findings")
    if not findings:
        lines.append("✅ **No high-risk vulnerabilities detected!** Code adheres to standard safety heuristics.")
    else:
        for idx, f in enumerate(findings, 1):
            icon = SEVERITY_ICONS.get(f.severity, "⚪")
            lines.append(f"### {idx}. {icon} {f.severity}: {f.title}")
            lines.append(f"- **Line:** {f.line}")
            lines.append(f"- **Trigger Snippet:** `{f.code_snippet}`")
            lines.append(f"- **Explanation:** {f.explanation}")
            lines.append(f"- **Why Dangerous:** {f.why}")
            lines.append(f"- **Remediation:** {f.recommendation}")
            if f.vulnerable_example and f.recommended_example:
                lines.append("")
                lines.append("```python")
                lines.append("# Vulnerable Code Pattern")
                lines.append(f.vulnerable_example)
                lines.append("")
                lines.append("# Recommended Secure Replacement")
                lines.append(f.recommended_example)
                lines.append("```")
            lines.append("")

    # Recommendations Section
    lines.append("## 🛡️ Recommended Security Checklist")
    lines.append("1. **Remove Non-Existent Libraries:** Verify all imports against official PyPI registries before deployment.")
    lines.append("2. **Use Parameterized SQL:** Always use driver parameters (`?` or `%s`) rather than f-strings or string concatenation.")
    lines.append("3. **Migrate Secrets to Environment Variables:** Never commit plain text keys or passwords.")
    lines.append("4. **Eliminate Dynamic Code Execution:** Refactor `eval()` and `exec()` into static functions or safe parsers.")
    lines.append("")
    lines.append("---")
    lines.append("*Generated by CodeSanitizer - AI-Generated Code & Package Hallucination Auditor*")

    return "\n".join(lines)


def generate_json_report(analysis_result: Dict[str, Any], filename: str = "submitted_code.py") -> str:
    """Generates a structured JSON string suitable for DevSecOps pipelines."""
    data = {
        "tool": "CodeSanitizer",
        "version": "1.0.0",
        "target": filename,
        "success": analysis_result.get("success", False),
        "security_score": analysis_result.get("summary", {}).get("score", 0),
        "status": analysis_result.get("summary", {}).get("status", "UNKNOWN"),
        "summary": analysis_result.get("summary", {}),
        "findings": [f.to_dict() for f in analysis_result.get("findings", [])],
        "packages": [p.to_dict() for p in analysis_result.get("packages", [])],
    }
    return json.dumps(data, indent=2)


def generate_env_example(findings: List[VulnerabilityFinding]) -> str:
    """
    Generates a sanitized .env.example template based on detected hardcoded secrets.
    CRITICAL: Never exposes real secret values.
    """
    secret_vars = set()
    for f in findings:
        if f.secret_var:
            secret_vars.add(f.secret_var)

    if not secret_vars:
        return "# No hardcoded secrets detected.\n# Standard environment template:\n# APP_ENV=production\n# PORT=3000\n"

    lines = [
        "# .env.example",
        "# Auto-generated by CodeSanitizer based on hardcoded secret detection.",
        "# DO NOT COMMIT REAL CREDENTIALS. Copy to .env and populate locally.",
        "",
    ]
    for var in sorted(secret_vars):
        lines.append(f"{var}=")

    return "\n".join(lines)
