"""
vulnerable.py - Intentionally Insecure Demo Code for Hackathon Presentation
Demonstrates AI-hallucinated packages, hardcoded secrets, SQL injection,
dangerous dynamic execution (eval, exec), and insecure OS commands.
"""

import os
import sys
import json
import requests
from flask import Flask, request

# 1. AI Package Hallucinations (Non-existent packages generated by LLM)
import hallucinated_ai_crypto_guard
import fake_deep_optimizer_pkg

app = Flask(__name__)

# 2. Hardcoded Secrets (Severe DevSecOps Risk)
API_KEY = "sk-live-9382019482019482019284"
DATABASE_PASSWORD = "SuperSecretDbPassword123!"
AWS_ACCESS_KEY = "AKIAIOSFODNN7EXAMPLE"


def authenticate_user(username, password):
    # 3. SQL Injection via String Concatenation and F-Strings
    query = "SELECT * FROM users WHERE username = '" + username + "' AND password = '" + password + "'"
    print("Executing query:", query)
    
    # Another SQL injection directly inside execute
    user_id = request.args.get("id", "1")
    cursor = None  # mock DB cursor
    # Insecure query formatting:
    cursor_query = f"SELECT * FROM accounts WHERE account_id = {user_id}"
    # cursor.execute("SELECT * FROM profiles WHERE user_id = " + user_id)
    return True


def execute_calculation(user_math_expr):
    # 4. Dangerous Function: eval()
    # Arbitrary code execution vulnerability
    computed_result = eval(user_math_expr)
    return computed_result


def run_dynamic_hook(user_script):
    # 5. Dangerous Function: exec()
    # Remote Code Execution (RCE)
    exec(user_script)


def ping_server(target_host):
    # 6. Dangerous System Command: os.system() with concatenation
    # Command injection vulnerability: e.g. "8.8.8.8; cat /etc/passwd"
    os.system("ping -c 1 " + target_host)


if __name__ == "__main__":
    print("Running vulnerable demonstration app...")
