import React, { useState, useEffect } from 'react';
import { Header } from './components/Header';
import { ScoreCard } from './components/ScoreCard';
import { PackageTable } from './components/PackageTable';
import { FindingsList } from './components/FindingsList';
import { ExportSection } from './components/ExportSection';
import { ProjectFilesViewer } from './components/ProjectFilesViewer';
import { AuditResult } from './types';
import { clientSideAudit } from './utils/clientAudit';
import {
  Search,
  Upload,
  ClipboardPaste,
  Play,
  RotateCcw,
  AlertCircle,
  FileCode2,
  FolderGit2,
  CheckCircle,
  Sparkles,
  Layers,
  ArrowRight
} from 'lucide-react';

const DEFAULT_VULNERABLE_CODE = `"""
vulnerable.py - Intentionally Insecure Demo Code for Hackathon Presentation
Demonstrates AI-hallucinated packages, hardcoded secrets, SQL injection,
dangerous dynamic execution (eval, exec), and insecure OS commands.
"""

import os
import sys
import json
import requests
from flask import Flask, request

# 1. AI Package Hallucinations (Non-existent packages generated by LLM)
import hallucinated_ai_crypto_guard
import fake_deep_optimizer_pkg

app = Flask(__name__)

# 2. Hardcoded Secrets (Severe DevSecOps Risk)
API_KEY = "sk-live-9382019482019482019284"
DATABASE_PASSWORD = "SuperSecretDbPassword123!"
AWS_ACCESS_KEY = "AKIAIOSFODNN7EXAMPLE"


def authenticate_user(username, password):
    # 3. SQL Injection via String Concatenation and F-Strings
    query = "SELECT * FROM users WHERE username = '" + username + "' AND password = '" + password + "'"
    print("Executing query:", query)
    
    # Another SQL injection directly inside execute
    user_id = request.args.get("id", "1")
    cursor = None  # mock DB cursor
    # Insecure query formatting:
    cursor_query = f"SELECT * FROM accounts WHERE account_id = {user_id}"
    return True


def execute_calculation(user_math_expr):
    # 4. Dangerous Function: eval()
    # Arbitrary code execution vulnerability
    computed_result = eval(user_math_expr)
    return computed_result


def run_dynamic_hook(user_script):
    # 5. Dangerous Function: exec()
    # Remote Code Execution (RCE)
    exec(user_script)


def ping_server(target_host):
    # 6. Dangerous System Command: os.system() with concatenation
    # Command injection vulnerability: e.g. "8.8.8.8; cat /etc/passwd"
    os.system("ping -c 1 " + target_host)


if __name__ == "__main__":
    print("Running vulnerable demonstration app...")
`;

const DEFAULT_SAFE_CODE = `"""
safe.py - Secure, Hardened Python Reference Implementation
Demonstrates remediation best practices: environment variables for secrets,
parameterized SQL queries, safe literal evaluation, and hardened subprocess execution.
"""

import os
import sys
import json
import ast
import subprocess
import requests

# 1. Secure Secret Management via Environment Variables
API_KEY = os.getenv("API_KEY", "")
DATABASE_PASSWORD = os.getenv("DATABASE_PASSWORD", "")
AWS_ACCESS_KEY = os.getenv("AWS_ACCESS_KEY", "")


def authenticate_user(cursor, username: str, password_hash: str):
    # 2. Parameterized SQL Query (Prevents SQL Injection)
    query = "SELECT id, username, role FROM users WHERE username = ? AND password_hash = ?"
    cursor.execute(query, (username, password_hash))
    return cursor.fetchone()


def execute_safe_calculation(user_math_expr: str):
    # 3. Safe parsing with ast.literal_eval (Restricted to safe Python literals)
    try:
        result = ast.literal_eval(user_math_expr)
        return result
    except (ValueError, SyntaxError) as err:
        return {"error": "Invalid mathematical expression format"}


def ping_server_safe(target_host: str):
    # 4. Safe Subprocess with shell=False and list arguments (Prevents command injection)
    if not target_host or any(char in target_host for char in [";", "&", "|", "\`", "$"]):
        raise ValueError("Invalid target host characters detected")

    result = subprocess.run(
        ["ping", "-c", "1", target_host],
        capture_output=True,
        text=True,
        check=False,
        shell=False
    )
    return result.returncode == 0


if __name__ == "__main__":
    print("Running secure reference application.")
`;

export default function App() {
  const [activeTab, setActiveTab] = useState<'dashboard' | 'architecture'>('dashboard');
  const [inputMode, setInputMode] = useState<'paste' | 'upload'>('paste');
  const [code, setCode] = useState<string>(DEFAULT_VULNERABLE_CODE);
  const [isScanning, setIsScanning] = useState<boolean>(false);
  const [scanResult, setScanResult] = useState<AuditResult | null>(null);
  const [scanError, setScanError] = useState<string | null>(null);
  const [engineUsed, setEngineUsed] = useState<string>('Python 3.10 AST');

  // Trigger initial scan automatically on mount for a zero-wait demo
  useEffect(() => {
    handleScan(DEFAULT_VULNERABLE_CODE);
  }, []);

  const handleScan = async (codeToScan = code) => {
    if (!codeToScan.trim()) {
      setScanError('Please provide Python code to audit.');
      setScanResult(null);
      return;
    }

    setScanError(null);
    setIsScanning(true);

    try {
      // 1. Attempt Backend Python AST Analyzer Execution
      const res = await fetch('/api/scan', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ code: codeToScan }),
      });

      if (res.ok) {
        const data = await res.json();
        if (data.success) {
          setScanResult(data);
          setEngineUsed('Python 3.10 AST + Live PyPI');
          setIsScanning(false);
          return;
        } else if (data.error_type === 'SYNTAX_ERROR') {
          setScanError(`❌ Invalid Python Syntax: ${data.message}`);
          setScanResult(null);
          setIsScanning(false);
          return;
        }
      }
    } catch (backendErr) {
      // Backend not running or offline, seamlessly use client-side audit engine
    }

    // 2. Client-Side Fallback Engine (with real-time PyPI API queries)
    try {
      const clientResult = await clientSideAudit(codeToScan);
      setScanResult(clientResult);
      setEngineUsed('Client AST Heuristics + PyPI API');
    } catch (err: any) {
      setScanError(`Audit failed: ${err.message || 'Unknown error'}`);
    } finally {
      setIsScanning(false);
    }
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (event) => {
        const content = event.target?.result as string;
        setCode(content);
        handleScan(content);
      };
      reader.readAsText(file);
    }
  };

  return (
    <div className="min-h-screen bg-slate-100/70 text-slate-800 flex flex-col font-sans">
      <Header />

      {/* Main Navigation Bar */}
      <div className="bg-white border-b border-slate-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex items-center justify-between">
          <div className="flex items-center gap-1 sm:gap-2">
            <button
              onClick={() => setActiveTab('dashboard')}
              className={`py-3.5 px-4 text-xs sm:text-sm font-bold border-b-2 flex items-center gap-2 transition-all ${
                activeTab === 'dashboard'
                  ? 'border-indigo-600 text-indigo-600'
                  : 'border-transparent text-slate-500 hover:text-slate-800'
              }`}
            >
              <FileCode2 className="w-4 h-4" />
              <span>Auditor Dashboard</span>
            </button>

            <button
              onClick={() => setActiveTab('architecture')}
              className={`py-3.5 px-4 text-xs sm:text-sm font-bold border-b-2 flex items-center gap-2 transition-all ${
                activeTab === 'architecture'
                  ? 'border-indigo-600 text-indigo-600'
                  : 'border-transparent text-slate-500 hover:text-slate-800'
              }`}
            >
              <FolderGit2 className="w-4 h-4" />
              <span>Codebase & Architecture (9 Files)</span>
            </button>
          </div>

          <div className="hidden sm:flex items-center gap-2 text-xs text-slate-500">
            <span className="inline-block w-2 h-2 rounded-full bg-emerald-500 animate-pulse" />
            <span className="font-medium">Active Engine: {engineUsed}</span>
          </div>
        </div>
      </div>

      {/* Main Content Area */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 flex-1 w-full space-y-6">
        {activeTab === 'architecture' ? (
          <ProjectFilesViewer />
        ) : (
          <>
            {/* Input & Code Section */}
            <div className="bg-white rounded-xl border border-slate-200 p-6 shadow-xs">
              <div className="flex flex-col md:flex-row md:items-center justify-between gap-3 mb-4">
                {/* Method selector */}
                <div className="flex items-center gap-2">
                  <span className="text-xs font-bold text-slate-600 uppercase tracking-wider">
                    Input Method:
                  </span>
                  <div className="inline-flex rounded-lg border border-slate-200 p-0.5 bg-slate-50">
                    <button
                      onClick={() => setInputMode('paste')}
                      className={`px-3 py-1 text-xs font-semibold rounded-md transition-all flex items-center gap-1.5 ${
                        inputMode === 'paste'
                          ? 'bg-white text-slate-900 shadow-xs'
                          : 'text-slate-500 hover:text-slate-800'
                      }`}
                    >
                      <ClipboardPaste className="w-3.5 h-3.5" />
                      Paste Code
                    </button>
                    <button
                      onClick={() => setInputMode('upload')}
                      className={`px-3 py-1 text-xs font-semibold rounded-md transition-all flex items-center gap-1.5 ${
                        inputMode === 'upload'
                          ? 'bg-white text-slate-900 shadow-xs'
                          : 'text-slate-500 hover:text-slate-800'
                      }`}
                    >
                      <Upload className="w-3.5 h-3.5" />
                      Upload .py File
                    </button>
                  </div>
                </div>

                {/* Quick Presets for Demo */}
                <div className="flex items-center gap-2 flex-wrap">
                  <span className="text-xs text-slate-400 font-medium">Quick Demo:</span>
                  <button
                    onClick={() => {
                      setCode(DEFAULT_VULNERABLE_CODE);
                      handleScan(DEFAULT_VULNERABLE_CODE);
                    }}
                    className="px-2.5 py-1 rounded-md text-xs font-bold bg-red-50 text-red-700 border border-red-200 hover:bg-red-100 transition-colors flex items-center gap-1"
                  >
                    🔴 Vulnerable Demo
                  </button>
                  <button
                    onClick={() => {
                      setCode(DEFAULT_SAFE_CODE);
                      handleScan(DEFAULT_SAFE_CODE);
                    }}
                    className="px-2.5 py-1 rounded-md text-xs font-bold bg-emerald-50 text-emerald-700 border border-emerald-200 hover:bg-emerald-100 transition-colors flex items-center gap-1"
                  >
                    🟢 Safe Demo
                  </button>
                  <button
                    onClick={() => {
                      setCode('');
                      setScanResult(null);
                      setScanError(null);
                    }}
                    className="px-2 py-1 rounded-md text-xs text-slate-500 hover:text-slate-800 hover:bg-slate-100 transition-colors flex items-center gap-1"
                    title="Clear editor"
                  >
                    <RotateCcw className="w-3 h-3" />
                    Clear
                  </button>
                </div>
              </div>

              {/* Upload Input */}
              {inputMode === 'upload' && (
                <div className="mb-4 p-4 rounded-lg border-2 border-dashed border-slate-300 hover:border-indigo-500 bg-slate-50 text-center transition-colors">
                  <input
                    type="file"
                    accept=".py"
                    onChange={handleFileUpload}
                    id="py-file-upload"
                    className="hidden"
                  />
                  <label
                    htmlFor="py-file-upload"
                    className="cursor-pointer flex flex-col items-center justify-center gap-1 text-xs"
                  >
                    <Upload className="w-6 h-6 text-slate-400" />
                    <span className="font-bold text-slate-700">Click to upload Python file (.py)</span>
                    <span className="text-slate-400">or drag and drop here</span>
                  </label>
                </div>
              )}

              {/* Code Text Area */}
              <div className="relative rounded-lg border border-slate-300 overflow-hidden focus-within:border-indigo-500 focus-within:ring-1 focus-within:ring-indigo-500">
                <div className="bg-slate-900 px-4 py-2 flex items-center justify-between text-xs text-slate-400 font-mono border-b border-slate-800">
                  <div className="flex items-center gap-2">
                    <span className="w-2.5 h-2.5 rounded-full bg-red-500 inline-block" />
                    <span className="w-2.5 h-2.5 rounded-full bg-yellow-500 inline-block" />
                    <span className="w-2.5 h-2.5 rounded-full bg-green-500 inline-block" />
                    <span className="ml-2 text-slate-300">submitted_code.py</span>
                  </div>
                  <span>{code.split('\n').length} lines · {code.length} chars</span>
                </div>

                <textarea
                  value={code}
                  onChange={(e) => setCode(e.target.value)}
                  placeholder="# Paste AI-generated Python code here to audit..."
                  rows={12}
                  className="w-full p-4 font-mono text-xs bg-slate-950 text-emerald-400 focus:outline-hidden resize-y leading-relaxed"
                  spellCheck={false}
                />
              </div>

              {/* Error Alert */}
              {scanError && (
                <div className="mt-4 p-3.5 rounded-lg bg-red-50 border border-red-200 text-red-800 text-xs flex items-start gap-2.5">
                  <AlertCircle className="w-4 h-4 text-red-600 shrink-0 mt-0.5" />
                  <div>
                    <span className="font-bold">Error Detected:</span> {scanError}
                  </div>
                </div>
              )}

              {/* Action Button */}
              <div className="mt-4 flex flex-col sm:flex-row items-center justify-between gap-3">
                <p className="text-xs text-slate-500">
                  Safe static analysis: Untrusted code is <strong>never executed</strong>.
                </p>
                <button
                  onClick={() => handleScan()}
                  disabled={isScanning}
                  className="w-full sm:w-auto px-6 py-2.5 rounded-lg bg-slate-900 text-white hover:bg-slate-800 font-bold text-xs flex items-center justify-center gap-2 shadow-sm transition-all disabled:opacity-50 cursor-pointer"
                >
                  {isScanning ? (
                    <>
                      <span className="w-3.5 h-3.5 border-2 border-white border-t-transparent rounded-full animate-spin" />
                      Analyzing AST & PyPI Registry...
                    </>
                  ) : (
                    <>
                      <Search className="w-4 h-4 text-emerald-400" />
                      <span>🔍 SCAN CODE</span>
                    </>
                  )}
                </button>
              </div>
            </div>

            {/* Results Display */}
            {scanResult && scanResult.success && (
              <div className="space-y-6">
                {/* 1. Security Score & Metrics */}
                <ScoreCard summary={scanResult.summary} />

                {/* 2. Live Package Verification */}
                <PackageTable packages={scanResult.packages} />

                {/* 3. Detailed Vulnerability Findings & Diffs */}
                <FindingsList findings={scanResult.findings} />

                {/* 4. Export & Sanitization Artifacts */}
                <ExportSection result={scanResult} />
              </div>
            )}
          </>
        )}
      </main>

      {/* Footer */}
      <footer className="border-t border-slate-200 bg-white py-4 mt-8">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col sm:flex-row items-center justify-between gap-2 text-xs text-slate-500">
          <div>
            <strong>CodeSanitizer</strong> — DevSecOps Hackathon Project · Built with Python 3.10+, Streamlit, AST & PyPI Live API
          </div>
          <div className="flex items-center gap-4">
            <span className="font-mono">streamlit run app.py</span>
            <span>•</span>
            <span className="text-emerald-600 font-medium">Ready for Hackathon Pitch</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
